language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-21  ANDROID_ABI=armeabi-v7a

android:
  components:
  #  - build-tools-21.1.1
  # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-21.1.1

    # The SDK version used to compile your project
    - android-21

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-21

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-21
    - sys-img-x86-android-1

before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  #- android-wait-for-emulator
  #- adb shell input keyevent 82 &
script:
  - ./android-wait-for-emulator
  - ./gradlew assemble